import { includes } from "lodash";

export const configPath = {
  dashboard: '/dashboard',
  user: 'user',
  userCreate: 'user/create',
  userDetail: 'user/:id',
  products: 'products',
  productCreate: 'products/create',
  productDetail: 'products/:id',
  blog: 'blog',
  blogCreate: 'blog/create',
  blogDetail: 'blog/:id',
  category: 'category',
  categoryCreate: 'category/create',
  categoryDetail: 'category/:id',
  nav: 'settings/nav',
  navCreate: 'settings/nav/create',
  navDetail: 'settings/nav/:id',
  webConfig: 'settings/web-config',
  seoConfig: 'settings/seo-config',
  warehouse: 'warehouse',
  warehouseCreate: 'warehouse/create',
  warehouseDetail: 'warehouse/:id',
  coupons: 'coupons',
  couponsCreate: 'coupons/create',
  couponsDetail: 'coupons/:id',
  orders: 'orders',
  orderDetail: 'orders/:id',
  suppliers: 'suppliers',
  supplierCreate: 'suppliers/create',
  supplierDetail: 'suppliers/:id',
  brands: 'brands',
  brandCreate: 'brands/create',
  brandDetail: 'brands/:id',
  webBanner: 'webBanners',
  webBannerCreate: 'webBanners/create',
  webBannerDetail: 'webBanners/:id',
};
export const arrPath = Object.values(configPath).filter((item) => !includes(item, ':'));