services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/nodemon.json:/app/nodemon.json
    environment:
      - MONGODB_URI=mongodb+srv://admin1:admin1@datn.5mgkgxf.mongodb.net/?retryWrites=true&w=majority&appName=datn
      - SECRET_STAFF=SECRET_STAFF
      - REDIS_URL=redis://redis:6379
      - DATABASE_NAME=datn
      - HOST_URL=3000
      - SECRET=SECRET
      - REFRESH_SECRET=REFRESH_SECRET
      - URL_FE=http://localhost:5173/
      - EMAIL_NODEMAILER=tuhvpk03455@fpt.edu.vn
      - PASSWORD_NODEMAILER=mock dhjs ckzi enei
      - CLIENT_URL=http://localhost:5173/
    command: npm run dev

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data

volumes:
  redis_data:
