services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - elasticsearch
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/nodemon.json:/app/nodemon.json
    environment:
      - SECRET_STAFF=your_secret_staff_key_here
      - REDIS_URL=redis://redis:6379
      - DATABASE_NAME=datn
      - HOST_URL=3000
      - SECRET=your_secret_key_here
      - REFRESH_SECRET=your_refresh_secret_key_here
      - URL_FE=http://localhost:5173
      - EMAIL_NODEMAILER=your_email@example.com
      - PASSWORD_NODEMAILER=your_app_password
      - CLIENT_URL=http://localhost:5173
    command: npm run dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    command: ["elasticsearch"]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
    command: ["kibana"]

volumes:
  redis_data:
  elasticsearch_data: